#!/usr/bin/env python3
"""
Example: Multi-app workflow via noVNC.

Full workflow: terminal → calculator → text editor → file manager → browser.
Demonstrates controlling multiple desktop apps in sequence with full logging.

Prerequisites:
    docker compose -f docker/novnc/docker-compose.yml up -d

Usage:
    python3 examples/06_desktop_automation/example_multi_app.py
"""

from __future__ import annotations
import sys, time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

from nlp2cmd.cli.session_logger import SessionLogger


def main():
    from playwright.sync_api import sync_playwright

    out = Path(__file__).parent
    logger = SessionLogger("multi_app_session", output_dir=out, thumbnail_width=256)
    logger.start(
        "Multi-App Desktop Automation",
        description="Control 5 different desktop applications in one session",
    )

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page(viewport={"width": 1280, "height": 800})

        page.goto("http://localhost:6080/vnc.html?autoconnect=true", timeout=15000)
        page.wait_for_timeout(4000)
        try:
            page.wait_for_selector("canvas", timeout=10000)
        except Exception:
            pass

        logger.section("Phase 1: System Reconnaissance")
        logger.step("Desktop connected", page=page)

        # 1. Terminal: gather system info
        page.keyboard.press("Control+Alt+t")
        page.wait_for_timeout(2000)
        logger.step("Terminal opened", page=page)

        for cmd in ["hostname", "uname -a", "date", "uptime"]:
            page.keyboard.type(cmd, delay=20)
            page.keyboard.press("Enter")
            page.wait_for_timeout(1000)
        logger.step("System info gathered", page=page)
        logger.code("hostname && uname -a && date && uptime")

        # 2. Calculator
        logger.section("Phase 2: Calculation")
        page.keyboard.type("galculator &", delay=30)
        page.keyboard.press("Enter")
        page.wait_for_timeout(2000)
        logger.step("Calculator launched", page=page)

        page.keyboard.type("1024*768", delay=80)
        page.keyboard.press("Enter")
        page.wait_for_timeout(800)
        logger.step("Calculated screen pixels: 1024×768 = 786432", page=page)

        # 3. Text editor
        logger.section("Phase 3: Documentation")
        page.keyboard.press("Alt+F2")
        page.wait_for_timeout(1000)
        page.keyboard.type("mousepad", delay=50)
        page.keyboard.press("Enter")
        page.wait_for_timeout(2000)
        logger.step("Text editor opened", page=page)

        report = "Automated System Report\n\nGenerated by NLP2CMD multi-app workflow.\n"
        page.keyboard.type(report, delay=8)
        page.wait_for_timeout(500)
        logger.step("Report typed", page=page)

        # 4. File manager
        logger.section("Phase 4: File Management")
        page.keyboard.press("Alt+F2")
        page.wait_for_timeout(1000)
        page.keyboard.type("thunar /home/nlp2cmd", delay=50)
        page.keyboard.press("Enter")
        page.wait_for_timeout(2000)
        logger.step("File manager opened at /home/nlp2cmd", page=page)

        # 5. Browser
        logger.section("Phase 5: Web Access")
        page.keyboard.press("Alt+F2")
        page.wait_for_timeout(1000)
        page.keyboard.type("firefox https://github.com/wronai/nlp2cmd", delay=25)
        page.keyboard.press("Enter")
        page.wait_for_timeout(5000)
        logger.step("Firefox opened GitHub page", page=page)

        # Final
        page.wait_for_timeout(2000)
        logger.step("Final state — all 5 apps running", page=page)

        browser.close()

    md_path = logger.end(summary={
        "Apps controlled": "Terminal, Calculator, Mousepad, Thunar, Firefox",
        "Total phases": 5,
        "Protocol": "Playwright → noVNC → TigerVNC → XFCE4",
    })
    print(f"\nReport: {md_path}")


if __name__ == "__main__":
    main()
