version: 1
stack_path: /home/tom/github/semcod/mcp
gateway_url: http://localhost:9000/v1
api_key_env: SEMCOD_MCP_API_KEY
default_api_key: sk-mcp-default-dev-key
repo_id: semcod/nlp2cmd
project_dir: /home/tom/github/semcod/nlp2cmd
ides:
- continue
- cursor
- vscode
- vscode-settings
- windsurf
initialized_at: '2026-06-18T14:22:58.285223+00:00'
last_synced_at: '2026-06-18T14:22:58.285223+00:00'
