"""
Browser domain templates for NLP2CMD.

Contains all browser/web automation templates.
"""

BROWSER_TEMPLATES = {
    'web_action': "# Browser action: {action} on {target}",
    'navigate': "xdg-open '{url}'",
    'click': "# Click: {element}",
    'search_google': "xdg-open 'https://www.google.com/search?q={query}'",
    'search_duckduckgo': "xdg-open 'https://duckduckgo.com/?q={query}'",
    'search_bing': "xdg-open 'https://www.bing.com/search?q={query}'",
    'search_stackoverflow': "xdg-open 'https://stackoverflow.com/search?q={query}'",
    'search_github': "xdg-open 'https://github.com/search?q={query}'",
    'search_wikipedia': "xdg-open 'https://en.wikipedia.org/wiki/{query}'",
    'search_youtube': "xdg-open 'https://www.youtube.com/results?search_query={query}'",
    'search_amazon': "xdg-open 'https://www.amazon.com/s?k={query}'",
    'open_gmail': "xdg-open 'https://mail.google.com'",
    'find_form': '{{ "dsl": "dom_dql.v1", "url": "{url}", "actions": [ {{ "action": "explore_for_form", "intent": "contact" }} ] }}',
    'explore_and_fill': '{{ "dsl": "dom_dql.v1", "url": "{url}", "actions": [ {{ "action": "explore_for_form", "intent": "contact" }}, {{ "action": "fill_form" }}, {{ "action": "submit" }} ] }}',
    'open_outlook': "xdg-open 'https://outlook.live.com'",
    'open_github': "xdg-open 'https://github.com'",
    'open_stackoverflow': "xdg-open 'https://stackoverflow.com'",
    'open_twitter': "xdg-open 'https://twitter.com'",
    'open_linkedin': "xdg-open 'https://linkedin.com'",
    'open_facebook': "xdg-open 'https://facebook.com'",
    'open_reddit': "xdg-open 'https://reddit.com'",
    'open_wikipedia': "xdg-open 'https://en.wikipedia.org'",
    'open_youtube': "xdg-open 'https://youtube.com'",
    'open_news': "xdg-open 'https://news.google.com'",
    'open_weather': "xdg-open 'https://weather.com'",
    'open_maps': "xdg-open 'https://maps.google.com'",
    'open_translate': "xdg-open 'https://translate.google.com'",
    'open_calculator': "xdg-open 'https://calculator.net'",
    'open_calendar': "xdg-open 'https://calendar.google.com'",
    'open_drive': "xdg-open 'https://drive.google.com'",
    'open_dropbox': "xdg-open 'https://dropbox.com'",
    'open_slack': "xdg-open 'https://slack.com'",
    'open_discord': "xdg-open 'https://discord.com'",
    'open_zoom': "xdg-open 'https://zoom.us'",
    'open_teams': "xdg-open 'https://teams.microsoft.com'",
    'open_notion': "xdg-open 'https://notion.so'",
    'open_trello': "xdg-open 'https://trello.com'",
    'open_asana': "xdg-open 'https://asana.com'",
    'open_jira': "xdg-open 'https://jira.atlassian.com'",
    'open_confluence': "xdg-open 'https://confluence.atlassian.com'",
    'open_bitbucket': "xdg-open 'https://bitbucket.org'",
    'open_gitlab': "xdg-open 'https://gitlab.com'",
    'open_dockerhub': "xdg-open 'https://hub.docker.com'",
    'open_aws': "xdg-open 'https://console.aws.amazon.com'",
    'open_azure': "xdg-open 'https://portal.azure.com'",
    'open_gcp': "xdg-open 'https://console.cloud.google.com'",
    'open_digitalocean': "xdg-open 'https://cloud.digitalocean.com'",
    'open_heroku': "xdg-open 'https://dashboard.heroku.com'",
    'open_vercel': "xdg-open 'https://vercel.com'",
    'open_netlify': "xdg-open 'https://app.netlify.com'",
    'open_github_pages': "xdg-open 'https://pages.github.com'",
    'open_codepen': "xdg-open 'https://codepen.io'",
    'open_jsfiddle': "xdg-open 'https://jsfiddle.net'",
    'open_codesandbox': "xdg-open 'https://codesandbox.io'",
    'open_replit': "xdg-open 'https://replit.com'",
    'open_stackblitz': "xdg-open 'https://stackblitz.com'",
}
