"""
Docker domain templates for NLP2CMD.

Contains all Docker-related command templates.
"""

DOCKER_TEMPLATES = {
    'list': "docker ps {flags}",
    'list_all': "docker ps -a",
    'images': "docker images {flags}",
    'pull': "docker pull {image}",
    'run': "docker run {flags} {image} {command}",
    'run_interactive': "docker run -it {flags} {image} {command}",
    'run_detached': "docker run -d {flags} {image} {command}",
    'run_volume': "docker run -v {volume}:{mount} {flags} {image} {command}",
    'run_port': "docker run -p {host_port}:{container_port} {flags} {image} {command}",
    'exec': "docker exec {flags} {container} {command}",
    'exec_interactive': "docker exec -it {container} {command}",
    'stop': "docker stop {container}",
    'start': "docker start {container}",
    'restart': "docker restart {container}",
    'remove': "docker rm {container}",
    'remove_force': "docker rm -f {container}",
    'remove_all': "docker rm -f $(docker ps -aq)",
    'kill': "docker kill {container}",
    'pause': "docker pause {container}",
    'unpause': "docker unpause {container}",
    'logs': "docker logs {flags} {container}",
    'logs_follow': "docker logs -f {container}",
    'inspect': "docker inspect {container}",
    'stats': "docker stats {flags}",
    'top': "docker top {container}",
    'diff': "docker diff {container}",
    'port': "docker port {container}",
    'commit': "docker commit {container} {image}",
    'tag': "docker tag {source_image} {target_image}",
    'push': "docker push {image}",
    'save': "docker save -o {file} {image}",
    'load': "docker load -i {file}",
    'export': "docker export -o {file} {container}",
    'import': "docker import {file} {image}",
    'build': "docker build {flags} -t {image} {path}",
    'build_context': "docker build {flags} -t {image} {context}",
    'login': "docker login {registry}",
    'logout': "docker logout {registry}",
    'search': "docker search {query}",
    'history': "docker history {image}",
    'create': "docker create {flags} {image} {command}",
    'cp': "docker cp {container}:{source} {destination}",
    'cp_to_container': "docker cp {source} {container}:{destination}",
    'rename': "docker rename {old_name} {new_name}",
    'update': "docker update {flags} {container}",
    'prune': "docker system prune -f",
    'prune_volumes': "docker volume prune -f",
    'prune_networks': "docker network prune -f",
    'prune_images': "docker image prune -f",
    'network_create': "docker network create {flags} {network}",
    'network_remove': "docker network rm {network}",
    'network_connect': "docker network connect {network} {container}",
    'network_disconnect': "docker network disconnect {network} {container}",
    'network_ls': "docker network ls",
    'network_inspect': "docker network inspect {network}",
    'volume_create': "docker volume create {flags} {volume}",
    'volume_remove': "docker volume rm {volume}",
    'volume_ls': "docker volume ls",
    'volume_inspect': "docker volume inspect {volume}",
    'compose_up': "docker-compose up {flags}",
    'compose_down': "docker-compose down {flags}",
    'compose_build': "docker-compose build {flags}",
    'compose_ps': "docker-compose ps {flags}",
    'compose_logs': "docker-compose logs {flags} {service}",
    'compose_exec': "docker-compose exec {service} {command}",
    'compose_stop': "docker-compose stop {flags}",
    'compose_start': "docker-compose start {flags}",
    'compose_restart': "docker-compose restart {flags}",
    'compose_pull': "docker-compose pull {flags}",
    'compose_config': "docker-compose config",
}
