"""
Git domain templates for NLP2CMD.

Contains all Git-related command templates.
"""

GIT_TEMPLATES = {
    'status': "git status",
    'status_short': "git status -s",
    'log': "git log --oneline -n {limit}",
    'log_full': "git log -n {limit}",
    'log_graph': "git log --graph --oneline -n {limit}",
    'log_stat': "git log --stat -n {limit}",
    'add': "git add {files}",
    'add_all': "git add .",
    'add_patch': "git add -p",
    'commit': "git commit -m '{message}'",
    'commit_amend': "git commit --amend",
    'commit_amend_no_edit': "git commit --amend --no-edit",
    'push': "git push {remote} {branch}",
    'push_force': "git push --force {remote} {branch}",
    'push_force_with_lease': "git push --force-with-lease {remote} {branch}",
    'push_upstream': "git push --set-upstream {remote} {branch}",
    'pull': "git pull {remote} {branch}",
    'pull_rebase': "git pull --rebase {remote} {branch}",
    'fetch': "git fetch {remote}",
    'fetch_all': "git fetch --all",
    'clone': "git clone {url} {directory}",
    'clone_shallow': "git clone --depth {depth} {url} {directory}",
    'branch': "git branch {name}",
    'branch_list': "git branch",
    'branch_list_remote': "git branch -r",
    'branch_list_all': "git branch -a",
    'branch_delete': "git branch -d {name}",
    'branch_delete_force': "git branch -D {name}",
    'checkout': "git checkout {branch}",
    'checkout_create': "git checkout -b {name}",
    'checkout_file': "git checkout {file}",
    'merge': "git merge {branch}",
    'merge_no_ff': "git merge --no-ff {branch}",
    'merge_squash': "git merge --squash {branch}",
    'rebase': "git rebase {branch}",
    'rebase_interactive': "git rebase -i {commit}",
    'rebase_continue': "git rebase --continue",
    'rebase_abort': "git rebase --abort",
    'reset': "git reset {commit}",
    'reset_hard': "git reset --hard {commit}",
    'reset_soft': "git reset --soft {commit}",
    'reset_mixed': "git reset --mixed {commit}",
    'stash': "git stash",
    'stash_pop': "git stash pop",
    'stash_apply': "git stash apply",
    'stash_list': "git stash list",
    'stash_show': "git stash show",
    'stash_drop': "git stash drop",
    'stash_clear': "git stash clear",
    'tag': "git tag {name}",
    'tag_annotated': "git tag -a {name} -m '{message}'",
    'tag_list': "git tag",
    'tag_delete': "git tag -d {name}",
    'tag_push': "git push {remote} {name}",
    'tag_push_all': "git push --tags",
    'remote_add': "git remote add {name} {url}",
    'remote_remove': "git remote remove {name}",
    'remote_rename': "git remote rename {old} {new}",
    'remote_list': "git remote",
    'remote_show': "git remote show {name}",
    'diff': "git diff",
    'diff_staged': "git diff --staged",
    'diff_cached': "git diff --cached",
    'diff_commit': "git diff {commit1} {commit2}",
    'diff_file': "git diff {file}",
    'show': "git show {commit}",
    'show_file': "git show {commit}:{file}",
    'blame': "git blame {file}",
    'grep': "git grep '{pattern}'",
    'grep_file': "git grep '{pattern}' {file}",
    'cherry_pick': "git cherry-pick {commit}",
    'cherry_pick_continue': "git cherry-pick --continue",
    'cherry_pick_abort': "git cherry-pick --abort",
    'revert': "git revert {commit}",
    'revert_no_edit': "git revert --no-edit {commit}",
    'clean': "git clean {flags}",
    'clean_dry': "git clean -n",
    'clean_force': "git clean -f",
    'clean_directories': "git clean -d",
    'gc': "git gc",
    'gc_aggressive': "git gc --aggressive",
    'prune': "git prune",
    'fsck': "git fsck",
    'count_objects': "git count-objects",
    'pack_refs': "git pack-refs",
    'config_get': "git config {key}",
    'config_set': "git config {key} '{value}'",
    'config_global': "git config --global {key} '{value}'",
    'config_local': "git config --local {key} '{value}'",
    'config_list': "git config --list",
    'config_unset': "git config --unset {key}",
    'init': "git init",
    'init_bare': "git init --bare",
    'submodule_add': "git submodule add {url} {path}",
    'submodule_update': "git submodule update",
    'submodule_init': "git submodule init",
    'submodule_sync': "git submodule sync",
    'submodule_remove': "git submodule remove {path}",
    'worktree_add': "git worktree add {path} {branch}",
    'worktree_remove': "git worktree remove {path}",
    'worktree_list': "git worktree list",
    'bisect_start': "git bisect start",
    'bisect_bad': "git bisect bad",
    'bisect_good': "git bisect good",
    'bisect_skip': "git bisect skip",
    'bisect_reset': "git bisect reset",
    'bisect_run': "git bisect run {command}",
}
