"""
Kubernetes domain templates for NLP2CMD.

Contains all Kubernetes-related command templates.
"""

KUBERNETES_TEMPLATES = {
    'get': "kubectl get {resource} {name} {namespace} {selector} {output}",
    'get_all': "kubectl get {resource} -A {output}",
    'describe': "kubectl describe {resource} {name} {namespace}",
    'create': "kubectl create -f {file}",
    'apply': "kubectl apply -f {file}",
    'delete': "kubectl delete {resource} {name} {namespace}",
    'delete_file': "kubectl delete -f {file}",
    'edit': "kubectl edit {resource} {name} {namespace}",
    'logs': "kubectl logs {name} {namespace} {flags}",
    'logs_follow': "kubectl logs -f {name} {namespace}",
    'exec': "kubectl exec {name} {namespace} -- {command}",
    'exec_interactive': "kubectl exec -it {name} {namespace} -- {command}",
    'port_forward': "kubectl port-forward {name} {local_port}:{remote_port} {namespace}",
    'scale': "kubectl scale {resource} {name} --replicas={replicas} {namespace}",
    'autoscale': "kubectl autoscale {resource} {name} --min={min} --max={max} {namespace}",
    'rollout_status': "kubectl rollout status {resource}/{name} {namespace}",
    'rollout_history': "kubectl rollout history {resource}/{name} {namespace}",
    'rollout_undo': "kubectl rollout undo {resource}/{name} {namespace}",
    'rollout_restart': "kubectl rollout restart {resource}/{name} {namespace}",
    'set_image': "kubectl set image {resource}/{name} {container}={image} {namespace}",
    'set_env': "kubectl set env {resource}/{name} {env_vars} {namespace}",
    'expose': "kubectl expose {resource} {name} --port={port} --target-port={target_port} {namespace}",
    'label': "kubectl label {resource} {name} {labels} {namespace}",
    'annotate': "kubectl annotate {resource} {name} {annotations} {namespace}",
    'cordon': "kubectl cordon {node}",
    'uncordon': "kubectl uncordon {node}",
    'drain': "kubectl drain {node} {flags}",
    'top_nodes': "kubectl top nodes",
    'top_pods': "kubectl top pods {namespace}",
    'config_use_context': "kubectl config use-context {context}",
    'config_set_context': "kubectl config set-context {context} --cluster={cluster} --user={user} --namespace={namespace}",
    'config_view': "kubectl config view",
    'config_current_context': "kubectl config current-context",
    'config_get_contexts': "kubectl config get-contexts",
    'config_get_clusters': "kubectl config get-clusters",
    'config_get_users': "kubectl config get-users",
    'apply_directory': "kubectl apply -f {directory}",
    'delete_directory': "kubectl delete -f {directory}",
    'diff': "kubectl diff -f {file}",
    'wait': "kubectl wait {resource} {name} --for condition={condition} --timeout={timeout} {namespace}",
    'cp': "kubectl cp {namespace}/{pod}:{source} {destination}",
    'cp_to_pod': "kubectl cp {source} {namespace}/{pod}:{destination}",
    'auth_can_i': "kubectl auth can-i {verb} {resource} {namespace}",
    'auth_reconcile': "kubectl auth reconcile -f {file}",
    'certificate_approve': "kubectl certificate approve {csr}",
    'certificate_deny': "kubectl certificate deny {csr}",
    'cluster_info': "kubectl cluster-info",
    'version': "kubectl version {flags}",
    'api_resources': "kubectl api-resources",
    'api_versions': "kubectl api-versions",
    'explain': "kubectl explain {resource}",
    'get_events': "kubectl get events {namespace} --sort-by={sort_by}",
    'get_secrets': "kubectl get secrets {namespace}",
    'get_configmaps': "kubectl get configmaps {namespace}",
    'get_services': "kubectl get services {namespace}",
    'get_deployments': "kubectl get deployments {namespace}",
    'get_pods': "kubectl get pods {namespace}",
    'get_nodes': "kubectl get nodes",
    'get_namespaces': "kubectl get namespaces",
    'get_ingress': "kubectl get ingress {namespace}",
    'get_pvc': "kubectl get pvc {namespace}",
    'get_pv': "kubectl get pv",
    'get_jobs': "kubectl get jobs {namespace}",
    'get_cronjobs': "kubectl get cronjobs {namespace}",
    'patch': "kubectl patch {resource} {name} -p '{patch}' {namespace}",
    'replace': "kubectl replace -f {file}",
    'proxy': "kubectl proxy {port}",
    'taint': "kubectl taint nodes {node} {taint}",
}
