"""
Package management domain templates for NLP2CMD.

Contains apt, yum/dnf, pip, npm, snap, flatpak, brew, cargo, go templates.
"""

PACKAGE_MGMT_TEMPLATES = {
    # apt (Debian/Ubuntu)
    'apt_install': "sudo apt-get install -y {package}",
    'apt_remove': "sudo apt-get remove {package}",
    'apt_purge': "sudo apt-get purge {package}",
    'apt_update': "sudo apt-get update",
    'apt_upgrade': "sudo apt-get upgrade -y",
    'apt_dist_upgrade': "sudo apt-get dist-upgrade -y",
    'apt_search': "apt-cache search {query}",
    'apt_info': "apt-cache show {package}",
    'apt_list_installed': "apt list --installed",
    'apt_autoremove': "sudo apt-get autoremove -y",
    'apt_clean': "sudo apt-get clean",
    'apt_add_repo': "sudo add-apt-repository {repository}",
    # yum/dnf (RHEL/Fedora)
    'dnf_install': "sudo dnf install -y {package}",
    'dnf_remove': "sudo dnf remove {package}",
    'dnf_update': "sudo dnf update -y",
    'dnf_search': "dnf search {query}",
    'dnf_info': "dnf info {package}",
    'dnf_list_installed': "dnf list installed",
    'yum_install': "sudo yum install -y {package}",
    'yum_remove': "sudo yum remove {package}",
    'yum_update': "sudo yum update -y",
    # pip (Python)
    'pip_install': "pip install {package}",
    'pip_install_version': "pip install {package}=={version}",
    'pip_install_requirements': "pip install -r {requirements}",
    'pip_uninstall': "pip uninstall -y {package}",
    'pip_upgrade': "pip install --upgrade {package}",
    'pip_list': "pip list",
    'pip_outdated': "pip list --outdated",
    'pip_freeze': "pip freeze > {output}",
    'pip_show': "pip show {package}",
    'pip_search': "pip index versions {package}",
    'pipx_install': "pipx install {package}",
    'pipx_run': "pipx run {package}",
    # npm (Node.js)
    'npm_install': "npm install {package}",
    'npm_install_global': "npm install -g {package}",
    'npm_install_dev': "npm install --save-dev {package}",
    'npm_uninstall': "npm uninstall {package}",
    'npm_update': "npm update",
    'npm_list': "npm list",
    'npm_list_global': "npm list -g --depth=0",
    'npm_outdated': "npm outdated",
    'npm_audit': "npm audit",
    'npm_audit_fix': "npm audit fix",
    'npm_init': "npm init -y",
    'npm_run': "npm run {script}",
    'npx_run': "npx {command}",
    # yarn
    'yarn_install': "yarn add {package}",
    'yarn_install_dev': "yarn add --dev {package}",
    'yarn_remove': "yarn remove {package}",
    'yarn_upgrade': "yarn upgrade {package}",
    # snap
    'snap_install': "sudo snap install {package}",
    'snap_install_classic': "sudo snap install --classic {package}",
    'snap_remove': "sudo snap remove {package}",
    'snap_list': "snap list",
    'snap_refresh': "sudo snap refresh",
    'snap_info': "snap info {package}",
    # flatpak
    'flatpak_install': "flatpak install -y {remote} {package}",
    'flatpak_remove': "flatpak uninstall {package}",
    'flatpak_list': "flatpak list",
    'flatpak_update': "flatpak update -y",
    'flatpak_search': "flatpak search {query}",
    'flatpak_run': "flatpak run {package}",
    # brew (macOS/Linux)
    'brew_install': "brew install {package}",
    'brew_uninstall': "brew uninstall {package}",
    'brew_update': "brew update && brew upgrade",
    'brew_search': "brew search {query}",
    'brew_info': "brew info {package}",
    'brew_list': "brew list",
    'brew_cask_install': "brew install --cask {package}",
    # cargo (Rust)
    'cargo_install': "cargo install {package}",
    'cargo_uninstall': "cargo uninstall {package}",
    'cargo_build': "cargo build --release",
    'cargo_run': "cargo run",
    'cargo_test': "cargo test",
    # go
    'go_install': "go install {package}@latest",
    'go_get': "go get {package}",
    'go_build': "go build -o {output} .",
    'go_run': "go run {file}",
    'go_test': "go test ./...",
    # system
    'which': "which {command}",
    'whereis': "whereis {command}",
    'dpkg_list': "dpkg -l | grep {pattern}",
    'dpkg_info': "dpkg -s {package}",
    'rpm_query': "rpm -qa | grep {pattern}",
    'rpm_info': "rpm -qi {package}",
}
