"""
Shell domain templates for NLP2CMD.

Contains all shell/command-line related templates.
"""

SHELL_TEMPLATES = {
    'file_operation': "sudo apt-get install {package}",
    'find': "find {path} {type_flag} {name_flag} {size_flag} {time_flag} {exec_flag}",
    'find_simple': "find {path} -name '{pattern}'",
    'count_files': "find '{path}' -maxdepth 1 -mindepth 1 -type f {name_flag_count} | wc -l",
    'count_dirs': "find '{path}' -maxdepth 1 -mindepth 1 -type d {name_flag_count} | wc -l",
    'list': "ls -la {path}",
    'list_recursive': "ls -laR {path}",
    'list_user_directories': "ls -la {path}",
    'list_dirs': "find {path} -maxdepth 1 -type d",
    'grep': "grep -r '{pattern}' {path}",
    'search': "grep -r '{pattern}' {path}",
    'grep_file': "grep '{pattern}' {file}",
    'process': "ps aux",
    'list_processes': "ps aux",
    'process_list': "ps aux | grep {process_name}",
    'process_top': "ps aux --sort=-%{metric} | head -n {limit}",
    'w': "cat /etc/passwd",  # Show system users
    'disk_usage': "df -h {path}",
    'dir_size': "du -sh {path}",
    'copy': "cp {flags} {source} {destination}",
    'move': "mv {source} {destination}",
    'remove': "rm {flags} {target}",
    'remove_all': "find . -name '*.{extension}' -delete",
    'create_dir': "mkdir {directory}",
    'copy_file': "cp {source} {destination}",
    'move_file': "mv {source} {destination}",
    'delete_file': "rm {file}",
    'create_directory': "mkdir {directory}",
    'create_file': "touch {file}",
    'rename': "mv {old_name} {new_name}",
    'show_size': "du -h {file_path}",
    'process_kill': "kill -9 {pid}",
    'process_monitor': "top",
    'process_find': "ps aux | grep {process_name}",
    'archive_tar': "tar -czvf {archive} {source}",
    'extract_tar': "tar -xzvf {archive} {destination}",
    'archive_zip': "zip -r {archive} {source}",
    'extract_zip': "unzip {archive} -d {destination}",
    # Polish-specific templates
    'file_search': "find {path} -name '*.{extension}' -type f",
    'file_content': "cat {file_path}",
    'file_tail': "tail -{lines} {file_path}",
    'file_size': "du -h {file_path}",
    'file_head': "head -{lines} {file_path}",
    'file_permissions': "ls -la {file_path}",
    'file_edit': "nano {file_path}",
    # Text processing
    'text_cat': "cat {file}",
    'text_cat_number': "cat -n {file}",
    'text_head': "head -n {lines} {file}",
    'text_tail': "tail -n {lines} {file}",
    'text_tail_follow': "tail -f {file}",
    'text_wc': "wc {file}",
    'text_wc_lines': "wc -l {file}",
    'text_wc_words': "wc -w {file}",
    'text_grep': "grep '{pattern}' {file}",
    'text_sed': "sed '{expression}' {file}",
    'text_awk': "awk '{expression}' {file}",
    'text_sort': "sort {file}",
    'text_unique': "sort {file} | uniq",
    # JSON processing
    'json_jq': "jq '{filter}' {file}",
    'json_jq_pretty': "jq '.' {file}",
    'json_jq_keys': "jq 'keys' {file}",
    # Network
    'network_ping': "ping -c {count} {host}",
    'network_curl': "curl {url}",
    'network_download': "curl -O {url}",
    'netstat': "netstat -tuln",
    'ss': "ss -tuln",
    # System monitoring
    'system_uptime': "uptime",
    'system_free': "free -h",
    'system_df': "df -h",
    'system_du': "du -sh {path}",
    'system_ps': "ps aux",
    'system_top': "top",
    'system_htop': "htop",
    # Permissions
    'permissions_chmod': "chmod {permissions} {file}",
    'permissions_chown': "chown {owner}:{group} {file}",
    # Package management
    'package_apt_install': "sudo apt-get install {package}",
    'package_apt_remove': "sudo apt-get remove {package}",
    'package_apt_update': "sudo apt-get update",
    'package_apt_upgrade': "sudo apt-get upgrade",
    'package_pip_install': "pip install {package}",
    'package_pip_uninstall': "pip uninstall {package}",
    # Backup
    'backup_rsync': "rsync -av {source} {destination}",
    'backup_cp': "cp -r {source} {destination}",
    # Compression
    'compress_gzip': "gzip {file}",
    'compress_gunzip': "gunzip {file}",
    'compress_tar': "tar -czf {archive} {source}",
    'compress_untar': "tar -xzf {archive}",
    # Parallel processing
    'parallel_xargs': "xargs -P {jobs} -I {} {command}",
    'parallel_gnu_parallel': "parallel -j {jobs} {command}",
}
