module: nlp.config.IntentConfig
type: functions
count: 2
functions:
  nlp.config.IntentConfig.get_examples:
    name: get_examples
    qualified_name: nlp.config.IntentConfig.get_examples
    file: /home/tom/github/wronai/nlp2cmd/src/nlp2cmd/nlp/config.py
    line: 131
    module: nlp.config
    class: IntentConfig
    is_method: true
    cfg_entry: nlp.config.IntentConfig.get_examples_entry
    calls:
    - self.examples.get
  nlp.config.IntentConfig.all_examples:
    name: all_examples
    qualified_name: nlp.config.IntentConfig.all_examples
    file: /home/tom/github/wronai/nlp2cmd/src/nlp2cmd/nlp/config.py
    line: 135
    module: nlp.config
    class: IntentConfig
    is_method: true
    cfg_entry: nlp.config.IntentConfig.all_examples_entry
    calls:
    - self.examples.values
    - result.extend
