module: nlp.config.ServiceRegistry
type: functions
count: 5
functions:
  nlp.config.ServiceRegistry.__init__:
    name: __init__
    qualified_name: nlp.config.ServiceRegistry.__init__
    file: /home/tom/github/wronai/nlp2cmd/src/nlp2cmd/nlp/config.py
    line: 62
    module: nlp.config
    class: ServiceRegistry
    is_method: true
    cfg_entry: nlp.config.ServiceRegistry.__init___entry
    calls:
    - self.load
  nlp.config.ServiceRegistry.load:
    name: load
    qualified_name: nlp.config.ServiceRegistry.load
    file: /home/tom/github/wronai/nlp2cmd/src/nlp2cmd/nlp/config.py
    line: 67
    module: nlp.config
    class: ServiceRegistry
    is_method: true
    cfg_entry: nlp.config.ServiceRegistry.load_entry
    calls:
    - data.get
    - services_data.items
    - log.debug
    - path.exists
    - log.warning
    - ServiceConfig
    - len
    - open
    - log.error
    - yaml.safe_load
    - cfg.get
  nlp.config.ServiceRegistry.get:
    name: get
    qualified_name: nlp.config.ServiceRegistry.get
    file: /home/tom/github/wronai/nlp2cmd/src/nlp2cmd/nlp/config.py
    line: 96
    module: nlp.config
    class: ServiceRegistry
    is_method: true
    cfg_entry: nlp.config.ServiceRegistry.get_entry
    calls:
    - self._services.get
    - name.lower
  nlp.config.ServiceRegistry.list_names:
    name: list_names
    qualified_name: nlp.config.ServiceRegistry.list_names
    file: /home/tom/github/wronai/nlp2cmd/src/nlp2cmd/nlp/config.py
    line: 100
    module: nlp.config
    class: ServiceRegistry
    is_method: true
    cfg_entry: nlp.config.ServiceRegistry.list_names_entry
    calls:
    - sorted
    - self._services.keys
  nlp.config.ServiceRegistry.as_planner_dict:
    name: as_planner_dict
    qualified_name: nlp.config.ServiceRegistry.as_planner_dict
    file: /home/tom/github/wronai/nlp2cmd/src/nlp2cmd/nlp/config.py
    line: 104
    module: nlp.config
    class: ServiceRegistry
    is_method: true
    cfg_entry: nlp.config.ServiceRegistry.as_planner_dict_entry
    calls:
    - svc.to_planner_dict
    - self._services.items
