# OutputFileManager - extracted from nlp2cmd_web_controller.py
"""
NLP2CMD Web Controller - Natural Language DevOps Layer.

This module provides a control plane that interprets natural language commands
to configure and manage web application infrastructure.

Example usage:
    controller = NLP2CMDWebController()
    
    # Deploy a chat service
    await controller.execute("Uruchom serwis czatu na porcie 8080 z Redis jako backend")
    
    # Configure email integration
    await controller.execute("Skonfiguruj klienta email dla konta jan@example.com")
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
import subprocess
import yaml
from dataclasses import dataclass, field
from typing import Any, Callable, Optional
from enum import Enum
from pathlib import Path
from datetime import datetime

sys.path.append(str(Path(__file__).resolve().parents[2]))
from _example_helpers import print_rule

# Import NLP2CMD core components
from nlp2cmd.core import NLP2CMD, LLMBackend
from nlp2cmd.generation.llm_simple import LiteLLMClient
from nlp2cmd.adapters.shell import ShellAdapter
from nlp2cmd.adapters.docker import DockerAdapter
from nlp2cmd.adapters.kubernetes import KubernetesAdapter

class OutputFileManager:
    """Manages saving generated configurations to files."""
    
    def __init__(self, output_dir: str = "./generated"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
    
    def save_docker_compose(self, compose_config: dict[str, Any], filename: str = "docker-compose.yml") -> str:
        """Save Docker Compose configuration to file."""
        filepath = self.output_dir / filename
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write("# Generated by NLP2CMD\n")
            f.write("# Natural Language to DevOps Configuration\n")
            f.write(f"# Generated at: {datetime.now().isoformat()}\n\n")
            yaml.dump(compose_config, f, default_flow_style=False, sort_keys=False)
        
        return str(filepath)
    
    def save_service_config(self, service_config: dict[str, Any], service_name: str) -> str:
        """Save individual service configuration to JSON file."""
        filepath = self.output_dir / f"{service_name}-config.json"
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(service_config, f, indent=2, ensure_ascii=False)
        
        return str(filepath)
    
    def save_deployment_plan(self, plan: dict[str, Any], name: str) -> str:
        """Save complete deployment plan to JSON file."""
        filepath = self.output_dir / f"{name}-deployment.json"
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(plan, f, indent=2, ensure_ascii=False)
        
        return str(filepath)
