module: automation.service_configs
type: orphan_nodes
count: 12
nodes:
  automation.service_configs._load_known_services_entry:
    id: automation.service_configs._load_known_services_entry
    type: ENTRY
    label: entry
    function: automation.service_configs._load_known_services
  automation.service_configs._load_known_services_exit:
    id: automation.service_configs._load_known_services_exit
    type: EXIT
    label: exit
    function: automation.service_configs._load_known_services
  automation.service_configs._load_known_services_return_318:
    id: automation.service_configs._load_known_services_return_318
    type: RETURN
    label: return
    function: automation.service_configs._load_known_services
    line: 318
  automation.service_configs._can_use_desktop_automation_entry:
    id: automation.service_configs._can_use_desktop_automation_entry
    type: ENTRY
    label: entry
    function: automation.service_configs._can_use_desktop_automation
  automation.service_configs._can_use_desktop_automation_exit:
    id: automation.service_configs._can_use_desktop_automation_exit
    type: EXIT
    label: exit
    function: automation.service_configs._can_use_desktop_automation
  automation.service_configs._can_use_desktop_automation_if_382:
    id: automation.service_configs._can_use_desktop_automation_if_382
    type: IF
    label: if
    function: automation.service_configs._can_use_desktop_automation
    line: 382
  automation.service_configs._can_use_desktop_automation_if_384:
    id: automation.service_configs._can_use_desktop_automation_if_384
    type: IF
    label: if
    function: automation.service_configs._can_use_desktop_automation
    line: 384
  automation.service_configs._can_use_desktop_automation_return_385:
    id: automation.service_configs._can_use_desktop_automation_return_385
    type: RETURN
    label: return
    function: automation.service_configs._can_use_desktop_automation
    line: 385
  automation.service_configs._can_use_desktop_automation_merge_384:
    id: automation.service_configs._can_use_desktop_automation_merge_384
    type: FUNC
    label: merge
    function: automation.service_configs._can_use_desktop_automation
  automation.service_configs._can_use_desktop_automation_return_391:
    id: automation.service_configs._can_use_desktop_automation_return_391
    type: RETURN
    label: return
    function: automation.service_configs._can_use_desktop_automation
    line: 391
  automation.service_configs._can_use_desktop_automation_merge_382:
    id: automation.service_configs._can_use_desktop_automation_merge_382
    type: FUNC
    label: merge
    function: automation.service_configs._can_use_desktop_automation
  automation.service_configs._can_use_desktop_automation_return_394:
    id: automation.service_configs._can_use_desktop_automation_return_394
    type: RETURN
    label: return
    function: automation.service_configs._can_use_desktop_automation
    line: 394
