module: appspec_runtime
type: orphan_nodes
count: 13
nodes:
  appspec_runtime.load_appspec_entry:
    id: appspec_runtime.load_appspec_entry
    type: ENTRY
    label: entry
    function: appspec_runtime.load_appspec
  appspec_runtime.load_appspec_exit:
    id: appspec_runtime.load_appspec_exit
    type: EXIT
    label: exit
    function: appspec_runtime.load_appspec
  appspec_runtime.load_appspec_if_37:
    id: appspec_runtime.load_appspec_if_37
    type: IF
    label: if
    function: appspec_runtime.load_appspec
    line: 37
  appspec_runtime.load_appspec_merge_37:
    id: appspec_runtime.load_appspec_merge_37
    type: FUNC
    label: merge
    function: appspec_runtime.load_appspec
  appspec_runtime.load_appspec_loop_41:
    id: appspec_runtime.load_appspec_loop_41
    type: FOR
    label: for
    function: appspec_runtime.load_appspec
    line: 41
  appspec_runtime.load_appspec_return_56:
    id: appspec_runtime.load_appspec_return_56
    type: RETURN
    label: return
    function: appspec_runtime.load_appspec
    line: 56
  appspec_runtime.get_action_entry:
    id: appspec_runtime.get_action_entry
    type: ENTRY
    label: entry
    function: appspec_runtime.get_action
  appspec_runtime.get_action_exit:
    id: appspec_runtime.get_action_exit
    type: EXIT
    label: exit
    function: appspec_runtime.get_action
  appspec_runtime.get_action_loop_27:
    id: appspec_runtime.get_action_loop_27
    type: FOR
    label: for
    function: appspec_runtime.get_action
    line: 27
  appspec_runtime.get_action_if_28:
    id: appspec_runtime.get_action_if_28
    type: IF
    label: if
    function: appspec_runtime.get_action
    line: 28
  appspec_runtime.get_action_return_29:
    id: appspec_runtime.get_action_return_29
    type: RETURN
    label: return
    function: appspec_runtime.get_action
    line: 29
  appspec_runtime.get_action_merge_28:
    id: appspec_runtime.get_action_merge_28
    type: FUNC
    label: merge
    function: appspec_runtime.get_action
  appspec_runtime.get_action_return_30:
    id: appspec_runtime.get_action_return_30
    type: RETURN
    label: return
    function: appspec_runtime.get_action
    line: 30
