module: environment
type: orphan_nodes
count: 98
nodes:
  environment.analyze_entry:
    id: environment.analyze_entry
    type: ENTRY
    label: entry
    function: environment.analyze
  environment.analyze_exit:
    id: environment.analyze_exit
    type: EXIT
    label: exit
    function: environment.analyze
  environment.analyze_return_141:
    id: environment.analyze_return_141
    type: RETURN
    label: return
    function: environment.analyze
    line: 141
  environment._get_os_info_entry:
    id: environment._get_os_info_entry
    type: ENTRY
    label: entry
    function: environment._get_os_info
  environment._get_os_info_exit:
    id: environment._get_os_info_exit
    type: EXIT
    label: exit
    function: environment._get_os_info
  environment._get_os_info_return_151:
    id: environment._get_os_info_return_151
    type: RETURN
    label: return
    function: environment._get_os_info
    line: 151
  environment._get_shell_info_entry:
    id: environment._get_shell_info_entry
    type: ENTRY
    label: entry
    function: environment._get_shell_info
  environment._get_shell_info_exit:
    id: environment._get_shell_info_exit
    type: EXIT
    label: exit
    function: environment._get_shell_info
  environment._get_shell_info_return_163:
    id: environment._get_shell_info_return_163
    type: RETURN
    label: return
    function: environment._get_shell_info
    line: 163
  environment._get_user_info_entry:
    id: environment._get_user_info_entry
    type: ENTRY
    label: entry
    function: environment._get_user_info
  environment._get_user_info_exit:
    id: environment._get_user_info_exit
    type: EXIT
    label: exit
    function: environment._get_user_info
  environment._get_user_info_if_171:
    id: environment._get_user_info_if_171
    type: IF
    label: if
    function: environment._get_user_info
    line: 171
  environment._get_user_info_merge_171:
    id: environment._get_user_info_merge_171
    type: FUNC
    label: merge
    function: environment._get_user_info
  environment._get_user_info_return_174:
    id: environment._get_user_info_return_174
    type: RETURN
    label: return
    function: environment._get_user_info
    line: 174
  environment._get_relevant_env_vars_entry:
    id: environment._get_relevant_env_vars_entry
    type: ENTRY
    label: entry
    function: environment._get_relevant_env_vars
  environment._get_relevant_env_vars_exit:
    id: environment._get_relevant_env_vars_exit
    type: EXIT
    label: exit
    function: environment._get_relevant_env_vars
  environment._get_relevant_env_vars_return_195:
    id: environment._get_relevant_env_vars_return_195
    type: RETURN
    label: return
    function: environment._get_relevant_env_vars
    line: 195
  environment.detect_tools_entry:
    id: environment.detect_tools_entry
    type: ENTRY
    label: entry
    function: environment.detect_tools
  environment.detect_tools_exit:
    id: environment.detect_tools_exit
    type: EXIT
    label: exit
    function: environment.detect_tools
  environment.detect_tools_if_210:
    id: environment.detect_tools_if_210
    type: IF
    label: if
    function: environment.detect_tools
    line: 210
  environment.detect_tools_merge_210:
    id: environment.detect_tools_merge_210
    type: FUNC
    label: merge
    function: environment.detect_tools
  environment.detect_tools_loop_215:
    id: environment.detect_tools_loop_215
    type: FOR
    label: for
    function: environment.detect_tools
    line: 215
  environment.detect_tools_if_221:
    id: environment.detect_tools_if_221
    type: IF
    label: if
    function: environment.detect_tools
    line: 221
  environment.detect_tools_if_223:
    id: environment.detect_tools_if_223
    type: IF
    label: if
    function: environment.detect_tools
    line: 223
  environment.detect_tools_if_225:
    id: environment.detect_tools_if_225
    type: IF
    label: if
    function: environment.detect_tools
    line: 225
  environment.detect_tools_merge_225:
    id: environment.detect_tools_merge_225
    type: FUNC
    label: merge
    function: environment.detect_tools
  environment.detect_tools_merge_223:
    id: environment.detect_tools_merge_223
    type: FUNC
    label: merge
    function: environment.detect_tools
  environment.detect_tools_merge_221:
    id: environment.detect_tools_merge_221
    type: FUNC
    label: merge
    function: environment.detect_tools
  environment.detect_tools_if_227:
    id: environment.detect_tools_if_227
    type: IF
    label: if
    function: environment.detect_tools
    line: 227
  environment.detect_tools_loop_252:
    id: environment.detect_tools_loop_252
    type: FOR
    label: for
    function: environment.detect_tools
    line: 252
  environment.detect_tools_merge_227:
    id: environment.detect_tools_merge_227
    type: FUNC
    label: merge
    function: environment.detect_tools
  environment.detect_tools_return_259:
    id: environment.detect_tools_return_259
    type: RETURN
    label: return
    function: environment.detect_tools
    line: 259
  environment.check_services_entry:
    id: environment.check_services_entry
    type: ENTRY
    label: entry
    function: environment.check_services
  environment.check_services_exit:
    id: environment.check_services_exit
    type: EXIT
    label: exit
    function: environment.check_services
  environment.check_services_loop_270:
    id: environment.check_services_loop_270
    type: FOR
    label: for
    function: environment.check_services
    line: 270
  environment.check_services_if_280:
    id: environment.check_services_if_280
    type: IF
    label: if
    function: environment.check_services
    line: 280
  environment.check_services_merge_280:
    id: environment.check_services_merge_280
    type: FUNC
    label: merge
    function: environment.check_services
  environment.check_services_if_285:
    id: environment.check_services_if_285
    type: IF
    label: if
    function: environment.check_services
    line: 285
  environment.check_services_merge_285:
    id: environment.check_services_merge_285
    type: FUNC
    label: merge
    function: environment.check_services
  environment.check_services_return_290:
    id: environment.check_services_return_290
    type: RETURN
    label: return
    function: environment.check_services
    line: 290
  environment._check_port_entry:
    id: environment._check_port_entry
    type: ENTRY
    label: entry
    function: environment._check_port
  environment._check_port_exit:
    id: environment._check_port_exit
    type: EXIT
    label: exit
    function: environment._check_port
  environment._check_docker_daemon_entry:
    id: environment._check_docker_daemon_entry
    type: ENTRY
    label: entry
    function: environment._check_docker_daemon
  environment._check_docker_daemon_exit:
    id: environment._check_docker_daemon_exit
    type: EXIT
    label: exit
    function: environment._check_docker_daemon
  environment.find_config_files_entry:
    id: environment.find_config_files_entry
    type: ENTRY
    label: entry
    function: environment.find_config_files
  environment.find_config_files_exit:
    id: environment.find_config_files_exit
    type: EXIT
    label: exit
    function: environment.find_config_files
  environment.find_config_files_if_330:
    id: environment.find_config_files_if_330
    type: IF
    label: if
    function: environment.find_config_files
    line: 330
  environment.find_config_files_merge_330:
    id: environment.find_config_files_merge_330
    type: FUNC
    label: merge
    function: environment.find_config_files
  environment.find_config_files_loop_347:
    id: environment.find_config_files_loop_347
    type: FOR
    label: for
    function: environment.find_config_files
    line: 347
  environment.find_config_files_if_349:
    id: environment.find_config_files_if_349
    type: IF
    label: if
    function: environment.find_config_files
    line: 349
  environment.find_config_files_merge_349:
    id: environment.find_config_files_merge_349
    type: FUNC
    label: merge
    function: environment.find_config_files
  environment.find_config_files_if_358:
    id: environment.find_config_files_if_358
    type: IF
    label: if
    function: environment.find_config_files
    line: 358
  environment.find_config_files_merge_358:
    id: environment.find_config_files_merge_358
    type: FUNC
    label: merge
    function: environment.find_config_files
  environment.find_config_files_loop_361:
    id: environment.find_config_files_loop_361
    type: FOR
    label: for
    function: environment.find_config_files
    line: 361
  environment.find_config_files_if_362:
    id: environment.find_config_files_if_362
    type: IF
    label: if
    function: environment.find_config_files
    line: 362
  environment.find_config_files_merge_362:
    id: environment.find_config_files_merge_362
    type: FUNC
    label: merge
    function: environment.find_config_files
  environment.find_config_files_return_370:
    id: environment.find_config_files_return_370
    type: RETURN
    label: return
    function: environment.find_config_files
    line: 370
  environment.validate_command_entry:
    id: environment.validate_command_entry
    type: ENTRY
    label: entry
    function: environment.validate_command
  environment.validate_command_exit:
    id: environment.validate_command_exit
    type: EXIT
    label: exit
    function: environment.validate_command
  environment.validate_command_if_391:
    id: environment.validate_command_if_391
    type: IF
    label: if
    function: environment.validate_command
    line: 391
  environment.validate_command_return_392:
    id: environment.validate_command_return_392
    type: RETURN
    label: return
    function: environment.validate_command
    line: 392
  environment.validate_command_merge_391:
    id: environment.validate_command_merge_391
    type: FUNC
    label: merge
    function: environment.validate_command
  environment.validate_command_if_398:
    id: environment.validate_command_if_398
    type: IF
    label: if
    function: environment.validate_command
    line: 398
  environment.validate_command_return_399:
    id: environment.validate_command_return_399
    type: RETURN
    label: return
    function: environment.validate_command
    line: 399
  environment.validate_command_merge_398:
    id: environment.validate_command_merge_398
    type: FUNC
    label: merge
    function: environment.validate_command
  environment.validate_command_if_403:
    id: environment.validate_command_if_403
    type: IF
    label: if
    function: environment.validate_command
    line: 403
  environment.validate_command_if_404:
    id: environment.validate_command_if_404
    type: IF
    label: if
    function: environment.validate_command
    line: 404
  environment.validate_command_merge_404:
    id: environment.validate_command_merge_404
    type: FUNC
    label: merge
    function: environment.validate_command
  environment.validate_command_merge_403:
    id: environment.validate_command_merge_403
    type: FUNC
    label: merge
    function: environment.validate_command
  environment.validate_command_if_408:
    id: environment.validate_command_if_408
    type: IF
    label: if
    function: environment.validate_command
    line: 408
  environment.validate_command_if_411:
    id: environment.validate_command_if_411
    type: IF
    label: if
    function: environment.validate_command
    line: 411
  environment.validate_command_if_413:
    id: environment.validate_command_if_413
    type: IF
    label: if
    function: environment.validate_command
    line: 413
  environment.validate_command_merge_413:
    id: environment.validate_command_merge_413
    type: FUNC
    label: merge
    function: environment.validate_command
  environment.validate_command_merge_411:
    id: environment.validate_command_merge_411
    type: FUNC
    label: merge
    function: environment.validate_command
  environment.validate_command_merge_408:
    id: environment.validate_command_merge_408
    type: FUNC
    label: merge
    function: environment.validate_command
  environment.validate_command_if_417:
    id: environment.validate_command_if_417
    type: IF
    label: if
    function: environment.validate_command
    line: 417
  environment.validate_command_if_420:
    id: environment.validate_command_if_420
    type: IF
    label: if
    function: environment.validate_command
    line: 420
  environment.validate_command_merge_420:
    id: environment.validate_command_merge_420
    type: FUNC
    label: merge
    function: environment.validate_command
  environment.validate_command_merge_417:
    id: environment.validate_command_merge_417
    type: FUNC
    label: merge
    function: environment.validate_command
  environment.validate_command_return_423:
    id: environment.validate_command_return_423
    type: RETURN
    label: return
    function: environment.validate_command
    line: 423
  environment.full_report_entry:
    id: environment.full_report_entry
    type: ENTRY
    label: entry
    function: environment.full_report
  environment.full_report_exit:
    id: environment.full_report_exit
    type: EXIT
    label: exit
    function: environment.full_report
  environment.full_report_return_438:
    id: environment.full_report_return_438
    type: RETURN
    label: return
    function: environment.full_report
    line: 438
  environment._get_resources_entry:
    id: environment._get_resources_entry
    type: ENTRY
    label: entry
    function: environment._get_resources
  environment._get_resources_exit:
    id: environment._get_resources_exit
    type: EXIT
    label: exit
    function: environment._get_resources
  environment._get_resources_return_481:
    id: environment._get_resources_return_481
    type: RETURN
    label: return
    function: environment._get_resources
    line: 481
  environment._generate_recommendations_entry:
    id: environment._generate_recommendations_entry
    type: ENTRY
    label: entry
    function: environment._generate_recommendations
  environment._generate_recommendations_exit:
    id: environment._generate_recommendations_exit
    type: EXIT
    label: exit
    function: environment._generate_recommendations
  environment._generate_recommendations_loop_493:
    id: environment._generate_recommendations_loop_493
    type: FOR
    label: for
    function: environment._generate_recommendations
    line: 493
  environment._generate_recommendations_if_494:
    id: environment._generate_recommendations_if_494
    type: IF
    label: if
    function: environment._generate_recommendations
    line: 494
  environment._generate_recommendations_merge_494:
    id: environment._generate_recommendations_merge_494
    type: FUNC
    label: merge
    function: environment._generate_recommendations
  environment._generate_recommendations_if_499:
    id: environment._generate_recommendations_if_499
    type: IF
    label: if
    function: environment._generate_recommendations
    line: 499
  environment._generate_recommendations_merge_499:
    id: environment._generate_recommendations_merge_499
    type: FUNC
    label: merge
    function: environment._generate_recommendations
  environment._generate_recommendations_if_511:
    id: environment._generate_recommendations_if_511
    type: IF
    label: if
    function: environment._generate_recommendations
    line: 511
  environment._generate_recommendations_if_513:
    id: environment._generate_recommendations_if_513
    type: IF
    label: if
    function: environment._generate_recommendations
    line: 513
  environment._generate_recommendations_merge_513:
    id: environment._generate_recommendations_merge_513
    type: FUNC
    label: merge
    function: environment._generate_recommendations
  environment._generate_recommendations_merge_511:
    id: environment._generate_recommendations_merge_511
    type: FUNC
    label: merge
    function: environment._generate_recommendations
  environment._generate_recommendations_return_516:
    id: environment._generate_recommendations_return_516
    type: RETURN
    label: return
    function: environment._generate_recommendations
    line: 516
