module: nlp.config.IntentConfig
type: orphan_nodes
count: 7
nodes:
  nlp.config.IntentConfig.get_examples_entry:
    id: nlp.config.IntentConfig.get_examples_entry
    type: ENTRY
    label: entry
    function: nlp.config.IntentConfig.get_examples
  nlp.config.IntentConfig.get_examples_exit:
    id: nlp.config.IntentConfig.get_examples_exit
    type: EXIT
    label: exit
    function: nlp.config.IntentConfig.get_examples
  nlp.config.IntentConfig.get_examples_return_133:
    id: nlp.config.IntentConfig.get_examples_return_133
    type: RETURN
    label: return
    function: nlp.config.IntentConfig.get_examples
    line: 133
  nlp.config.IntentConfig.all_examples_entry:
    id: nlp.config.IntentConfig.all_examples_entry
    type: ENTRY
    label: entry
    function: nlp.config.IntentConfig.all_examples
  nlp.config.IntentConfig.all_examples_exit:
    id: nlp.config.IntentConfig.all_examples_exit
    type: EXIT
    label: exit
    function: nlp.config.IntentConfig.all_examples
  nlp.config.IntentConfig.all_examples_loop_138:
    id: nlp.config.IntentConfig.all_examples_loop_138
    type: FOR
    label: for
    function: nlp.config.IntentConfig.all_examples
    line: 138
  nlp.config.IntentConfig.all_examples_return_140:
    id: nlp.config.IntentConfig.all_examples_return_140
    type: RETURN
    label: return
    function: nlp.config.IntentConfig.all_examples
    line: 140
